save_dir: save/
model_name: BertQA
model_weights: rubentito/bert-large-mpdocvqa
device: cuda
data_parallel: False
max_sequence_length: 512

training_parameters:
  lr: 5e-5
  batch_size: 32
  train_epochs: 10
  warmup_iterations: 1000
