save_dir: save/
model_name: BigBird
model_weights: rubentito/bigbird-base-itc-mpdocvqa
device: cuda
data_parallel: False

training_parameters:
  lr: 3e-5
  batch_size: 8
  train_epochs: 10
  warmup_iterations: 1000
