save_dir: save/
model_name: Longformer
# model_weights: valhalla/longformer-base-4096-finetuned-squadv1  # Best pretrained.
# model_weights: mrm8488/longformer-base-4096-finetuned-squadv2
# model_weights: allenai/longformer-base-4096-finetuned-triviaqa
model_weights: weights/longformer_oracle_mp-docvqa__best.ckpt
device: cuda
data_parallel: False

training_parameters:
  lr: 1e-4  # 2e-4
  batch_size: 3
  train_epochs: 10
  warmup_iterations: 1000
